### ISSUE TITLE
Does this adapter still work?

### ISSUE THREAD

**Issue by gep13** [kcjpop/hubot-gitter#5]
I have been trying to run this adapter on heroku for interacting with one of my Gitter rooms, but I can't seem to get it to work.

These are the commands that I have used:

```
heroku login
cd C:\heroku
mkdir chocobot
cd .\chocobot
yo hubot
npm install --save hubot-gitter
git init
git add .
git commit -m "Initial commit"
heroku create
heroku config:set TOKEN=***
heroku config:set HEROKU_URL=https://peaceful-taiga-8324.herokuapp.com/
heroku config:set ROOM=chocolatey/choco
git push heroku master
```

If I do `heroku logs` I get the following output:

![image](https://cloud.githubusercontent.com/assets/1271146/5889021/47f5f082-a40b-11e4-951e-ddc4658bd29d.png)

So it seems to be running, but I never get anything back from typing in to the chat room, with either:

```
hubot ping
```

or

```
chocobot ping
```

Can you offer any help in getting this to work?

Thanks!

**Comment by gep13** [comment]
Please ignore this issue, I have been able to get the gitter2 adapter working, so I will stick with that for just now. Thanks!

**Comment by kcjpop** [comment]
@gep13 Sorry, I'm quite busy with other stuff so this adapter has not been maintained for a long time.

**Comment by gep13** [comment]
@kcjpop Not a problem at all, totally understand.  We are quite happy now, having got the gitter2 adapter up and running.

Thanks
